/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package wetterServicePackage;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Operands implements org.apache.thrift.TBase<Operands, Operands._Fields>, java.io.Serializable, Cloneable, Comparable<Operands> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Operands");

  private static final org.apache.thrift.protocol.TField OPERAND_A_FIELD_DESC = new org.apache.thrift.protocol.TField("operand_a", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField OPERAND_B_FIELD_DESC = new org.apache.thrift.protocol.TField("operand_b", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new OperandsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new OperandsTupleSchemeFactory());
  }

  public int operand_a; // required
  public int operand_b; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OPERAND_A((short)1, "operand_a"),
    OPERAND_B((short)2, "operand_b");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // OPERAND_A
          return OPERAND_A;
        case 2: // OPERAND_B
          return OPERAND_B;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __OPERAND_A_ISSET_ID = 0;
  private static final int __OPERAND_B_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.OPERAND_A, new org.apache.thrift.meta_data.FieldMetaData("operand_a", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.OPERAND_B, new org.apache.thrift.meta_data.FieldMetaData("operand_b", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Operands.class, metaDataMap);
  }

  public Operands() {
  }

  public Operands(
    int operand_a,
    int operand_b)
  {
    this();
    this.operand_a = operand_a;
    setOperand_aIsSet(true);
    this.operand_b = operand_b;
    setOperand_bIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Operands(Operands other) {
    __isset_bitfield = other.__isset_bitfield;
    this.operand_a = other.operand_a;
    this.operand_b = other.operand_b;
  }

  public Operands deepCopy() {
    return new Operands(this);
  }

  @Override
  public void clear() {
    setOperand_aIsSet(false);
    this.operand_a = 0;
    setOperand_bIsSet(false);
    this.operand_b = 0;
  }

  public int getOperand_a() {
    return this.operand_a;
  }

  public Operands setOperand_a(int operand_a) {
    this.operand_a = operand_a;
    setOperand_aIsSet(true);
    return this;
  }

  public void unsetOperand_a() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __OPERAND_A_ISSET_ID);
  }

  /** Returns true if field operand_a is set (has been assigned a value) and false otherwise */
  public boolean isSetOperand_a() {
    return EncodingUtils.testBit(__isset_bitfield, __OPERAND_A_ISSET_ID);
  }

  public void setOperand_aIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __OPERAND_A_ISSET_ID, value);
  }

  public int getOperand_b() {
    return this.operand_b;
  }

  public Operands setOperand_b(int operand_b) {
    this.operand_b = operand_b;
    setOperand_bIsSet(true);
    return this;
  }

  public void unsetOperand_b() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __OPERAND_B_ISSET_ID);
  }

  /** Returns true if field operand_b is set (has been assigned a value) and false otherwise */
  public boolean isSetOperand_b() {
    return EncodingUtils.testBit(__isset_bitfield, __OPERAND_B_ISSET_ID);
  }

  public void setOperand_bIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __OPERAND_B_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case OPERAND_A:
      if (value == null) {
        unsetOperand_a();
      } else {
        setOperand_a((Integer)value);
      }
      break;

    case OPERAND_B:
      if (value == null) {
        unsetOperand_b();
      } else {
        setOperand_b((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case OPERAND_A:
      return Integer.valueOf(getOperand_a());

    case OPERAND_B:
      return Integer.valueOf(getOperand_b());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case OPERAND_A:
      return isSetOperand_a();
    case OPERAND_B:
      return isSetOperand_b();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Operands)
      return this.equals((Operands)that);
    return false;
  }

  public boolean equals(Operands that) {
    if (that == null)
      return false;

    boolean this_present_operand_a = true;
    boolean that_present_operand_a = true;
    if (this_present_operand_a || that_present_operand_a) {
      if (!(this_present_operand_a && that_present_operand_a))
        return false;
      if (this.operand_a != that.operand_a)
        return false;
    }

    boolean this_present_operand_b = true;
    boolean that_present_operand_b = true;
    if (this_present_operand_b || that_present_operand_b) {
      if (!(this_present_operand_b && that_present_operand_b))
        return false;
      if (this.operand_b != that.operand_b)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(Operands other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetOperand_a()).compareTo(other.isSetOperand_a());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperand_a()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operand_a, other.operand_a);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOperand_b()).compareTo(other.isSetOperand_b());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperand_b()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operand_b, other.operand_b);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Operands(");
    boolean first = true;

    sb.append("operand_a:");
    sb.append(this.operand_a);
    first = false;
    if (!first) sb.append(", ");
    sb.append("operand_b:");
    sb.append(this.operand_b);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class OperandsStandardSchemeFactory implements SchemeFactory {
    public OperandsStandardScheme getScheme() {
      return new OperandsStandardScheme();
    }
  }

  private static class OperandsStandardScheme extends StandardScheme<Operands> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Operands struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // OPERAND_A
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.operand_a = iprot.readI32();
              struct.setOperand_aIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OPERAND_B
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.operand_b = iprot.readI32();
              struct.setOperand_bIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Operands struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(OPERAND_A_FIELD_DESC);
      oprot.writeI32(struct.operand_a);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(OPERAND_B_FIELD_DESC);
      oprot.writeI32(struct.operand_b);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class OperandsTupleSchemeFactory implements SchemeFactory {
    public OperandsTupleScheme getScheme() {
      return new OperandsTupleScheme();
    }
  }

  private static class OperandsTupleScheme extends TupleScheme<Operands> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Operands struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetOperand_a()) {
        optionals.set(0);
      }
      if (struct.isSetOperand_b()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetOperand_a()) {
        oprot.writeI32(struct.operand_a);
      }
      if (struct.isSetOperand_b()) {
        oprot.writeI32(struct.operand_b);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Operands struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.operand_a = iprot.readI32();
        struct.setOperand_aIsSet(true);
      }
      if (incoming.get(1)) {
        struct.operand_b = iprot.readI32();
        struct.setOperand_bIsSet(true);
      }
    }
  }

}

