/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package wetterServicePackage;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * This Enum defines different weather warnings the system can return when a warning is requested
 */
public enum WeatherWarning implements org.apache.thrift.TEnum {
  NONE(0),
  BLIZZARD(1),
  FLOOD(2),
  HURRICANE(3),
  STORM(4),
  TORNADO(5),
  UV(6);

  private final int value;

  private WeatherWarning(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static WeatherWarning findByValue(int value) { 
    switch (value) {
      case 0:
        return NONE;
      case 1:
        return BLIZZARD;
      case 2:
        return FLOOD;
      case 3:
        return HURRICANE;
      case 4:
        return STORM;
      case 5:
        return TORNADO;
      case 6:
        return UV;
      default:
        return null;
    }
  }
}
